// --- SECTION 2: EXERCISE DATA LIBRARIES ---

// V8 CHANGE: New priority map for exercise selection
export const equipmentPriority = {
    barbell: 5,
    dumbbells_pair: 4,
    dumbbells_single: 3,
    pullup_bar: 3,
    bands: 2,
    bodyweight: 1
};

// V9 CHANGE: Exercise library fully updated with difficulty tags, baseVolume, and new core exercises
export const exerciseLibrary = {
    'Warmup': {
        bodyweight: [
            { id: 'warmup_jumping_jacks', content: 'Jumping Jacks', details: '60-90 seconds', duration: 90, type: 'info', requires: ['bodyweight'], tags: ['cardio', 'full body'], primaryMuscle: 'full_body', movementPattern: 'dynamic', difficulty: 'beginner', description: '1. Stand with your feet together and your arms at your sides. 2. In one motion, jump your feet out to the side and raise your arms above your head. 3. Immediately reverse that motion to jump back to the starting position.' },
            { id: 'warmup_cat_cow', content: 'Cat-Cow Stretch', details: '60 seconds', duration: 60, type: 'info', requires: ['bodyweight'], tags: ['mobility', 'spine'], primaryMuscle: 'spine', movementPattern: 'flexion_extension', difficulty: 'beginner', description: '1. Start on your hands and knees. 2. Inhale as you drop your belly towards the mat and look up (Cow). 3. Exhale as you round your spine, tuck your chin to your chest, and press the mat away (Cat).' },
            { id: 'warmup_leg_swings', content: 'Leg Swings', details: '30s each side', duration: 60, type: 'info', requires: ['bodyweight'], tags: ['mobility', 'hips', 'dynamic'], primaryMuscle: 'hips', movementPattern: 'hinge', difficulty: 'beginner', description: '1. Stand holding onto a stable surface for balance. 2. Swing one leg forward and backward like a pendulum, keeping your core tight. 3. Perform for 30 seconds, then switch legs.' },
            { id: 'warmup_arm_circles', content: 'Arm Circles', details: '30s each way', duration: 60, type: 'info', requires: ['bodyweight'], tags: ['mobility', 'shoulders', 'dynamic'], primaryMuscle: 'shoulders', movementPattern: 'rotation', difficulty: 'beginner', description: '1. Stand with your feet shoulder-width apart and extend your arms straight out to your sides. 2. Slowly rotate your arms forward in small circles for 30 seconds, then backward for 30 seconds.' },
            { id: 'warmup_spiderman_lunge_rotation', content: 'Spiderman Lunge with Thoracic Rotation', details: '3-5 reps per side', type: 'info', requires: ['bodyweight'], tags: ['mobility', 'hips', 'spine'], primaryMuscle: 'hips', movementPattern: 'lunge', difficulty: 'beginner', description: '1. Step into a deep lunge with your right foot forward. 2. Place your left hand on the ground and your right elbow inside your right foot. 3. Rotate your chest to the right, reaching your right arm to the ceiling. 4. Return to start and switch sides.' },
            { id: 'warmup_wall_slides', content: 'Wall Slides', details: '10-12 reps', type: 'info', requires: ['bodyweight'], tags: ['mobility', 'shoulders'], primaryMuscle: 'shoulders', movementPattern: 'push_vertical', difficulty: 'beginner', description: '1. Stand with your back against a wall, feet slightly away. 2. Place your arms against the wall in a "goalpost" position. 3. Slowly slide your arms up the wall, keeping your forearms and wrists in contact. 4. Slide back down to the start.' },
            { id: 'warmup_jump_squats_low', content: 'Jump Squats (low intensity)', details: '5-8 reps', type: 'info', requires: ['bodyweight'], tags: ['potentiation', 'legs'], primaryMuscle: 'quadriceps', movementPattern: 'squat', difficulty: 'beginner', description: '1. Perform a bodyweight squat to about half depth. 2. From the bottom, explode upwards into a small jump. 3. Land softly and immediately lower into the next squat.' },
            { id: 'warmup_broad_jumps', content: 'Broad Jumps', details: '3-5 reps', type: 'info', requires: ['bodyweight'], tags: ['potentiation', 'legs'], primaryMuscle: 'hamstrings', movementPattern: 'hinge', difficulty: 'beginner', description: '1. Stand with feet shoulder-width apart. 2. Hinge at your hips, swing your arms back, and jump forward as far as possible. 3. Land softly with your knees bent.' },
        ],
        bands: [
            { id: 'warmup_band_pull_aparts', content: 'Band Pull-Aparts', details: '15-20 reps', type: 'info', requires: ['bands'], tags: ['activation', 'shoulders'], primaryMuscle: 'rear_deltoid', movementPattern: 'pull_horizontal', difficulty: 'beginner', description: '1. Hold a resistance band with both hands, palms facing down, hands shoulder-width apart. 2. Keeping your arms straight, pull the band apart by squeezing your shoulder blades together. 3. Return to the starting position with control.' },
        ]
    },
    'Cooldown': {
        bodyweight: [
            { id: 'cooldown_childs_pose', content: 'Child\'s Pose', details: '60 seconds', duration: 60, type: 'info', requires: ['bodyweight'], tags: ['mobility', 'lower back', 'static'], primaryMuscle: 'spine', movementPattern: 'flexion_extension', difficulty: 'beginner', description: '1. Kneel on the floor, sit back on your heels, then fold forward, resting your forehead on the floor. 2. Extend your arms in front of you or rest them alongside your body. 3. Breathe deeply, feeling a gentle stretch in your back and hips.' },
            { id: 'cooldown_quad_stretch', content: 'Standing Quad Stretch', details: '30s each leg', duration: 60, type: 'info', requires: ['bodyweight'], tags: ['stretch', 'quads', 'static'], primaryMuscle: 'quadriceps', movementPattern: 'stretch', difficulty: 'beginner', description: '1. Stand on one leg, holding onto something for balance if needed. 2. Grab your other foot and gently pull your heel towards your glute. 3. Keep your knees together and feel the stretch in the front of your thigh. Hold for 30 seconds and switch sides.' },
            { id: 'cooldown_hamstring_stretch', content: 'Standing Hamstring Stretch', details: '30s each leg', duration: 60, type: 'info', requires: ['bodyweight'], tags: ['stretch', 'hamstrings', 'static'], primaryMuscle: 'hamstrings', movementPattern: 'stretch', difficulty: 'beginner', description: '1. Stand with your feet together. Step one foot forward and place the heel on the ground, keeping that leg straight. 2. Hinge at your hips and lean forward until you feel a stretch in the back of your front leg. 3. Hold for 30 seconds and switch sides.' },
            { id: 'cooldown_pigeon_pose', content: 'Pigeon Pose', details: '45s each side', duration: 90, type: 'info', requires: ['bodyweight'], tags: ['mobility', 'hips', 'glutes', 'static'], primaryMuscle: 'glutes', movementPattern: 'stretch', difficulty: 'beginner', description: '1. From a plank position, bring your right knee forward towards your right wrist. 2. Extend your left leg straight back behind you. 3. Keep your hips square and fold forward over your front leg if comfortable. Hold for 45 seconds and switch sides.' },
        ]
    },
    'Chest': {
        barbell: [{ id: 'ex_bench_press', content: 'Barbell Bench Press', type: 'log', target: { sets: 3, minReps: 5, maxReps: 8 }, weight: 40, baseVolume: { weight: 40, reps: 7 }, requires: ['barbell', 'bench'], history: [], pro_tip: "Keep your shoulder blades retracted and pinched together to protect your shoulders and maximize chest activation.", primaryMuscle: 'pectorals', secondaryMuscles: ['triceps', 'anterior_deltoid'], movementPattern: 'push_horizontal', difficulty: 'advanced', progression: 'ex_db_bench_press', regression: null, environment: 'gym', description: '1. Lie on a flat bench with your feet firmly on the floor. 2. Grip the barbell with hands slightly wider than shoulder-width. 3. Lower the bar to your mid-chest, keeping your elbows tucked at about a 45-degree angle. 4. Press the bar back up to the starting position.' }],
        dumbbells_pair: [
            { id: 'ex_db_bench_press', content: 'Dumbbell Bench Press', type: 'log', target: { sets: 3, minReps: 8, maxReps: 12 }, weight: 15, baseVolume: { weight: 15, reps: 10 }, requires: ['dumbbells_pair', 'bench'], history: [], primaryMuscle: 'pectorals', secondaryMuscles: ['triceps', 'anterior_deltoid'], movementPattern: 'push_horizontal', difficulty: 'intermediate', progression: 'ex_pushup', regression: 'ex_bench_press', environment: 'all', description: '1. Lie on a flat bench holding a dumbbell in each hand at your chest. 2. Press the dumbbells up until your arms are fully extended. 3. Lower the dumbbells slowly and with control to the sides of your chest.' },
            { id: 'ex_db_incline_press', content: 'Dumbbell Incline Press', type: 'log', target: { sets: 3, minReps: 8, maxReps: 12 }, weight: 12, baseVolume: { weight: 12, reps: 10 }, requires: ['dumbbells_pair', 'bench'], history: [], primaryMuscle: 'upper_pectorals', secondaryMuscles: ['anterior_deltoid', 'triceps'], movementPattern: 'push_incline', difficulty: 'intermediate', progression: 'ex_incline_pushup', regression: null, environment: 'all', description: '1. Lie on a bench set to a 30-45 degree incline. 2. Hold a dumbbell in each hand at your upper chest. 3. Press the dumbbells up and slightly back until your arms are extended. 4. Lower the dumbbells slowly to the starting position.' }
        ],
        bodyweight: [
            { id: 'ex_pushup', content: 'Push-ups', type: 'log', target: { sets: 3, toFailure: true }, weight: 0, baseVolume: { weight: 0, reps: 15 }, requires: ['bodyweight'], history: [], pro_tip: "Maintain a straight line from your head to your heels. Don't let your hips sag.", primaryMuscle: 'pectorals', secondaryMuscles: ['triceps', 'anterior_deltoid'], movementPattern: 'push_horizontal', difficulty: 'intermediate', progression: 'ex_incline_pushup', regression: 'ex_decline_pushup', environment: 'all', description: '1. Start in a high plank position with hands slightly wider than your shoulders. 2. Keep your body in a straight line from head to heels. 3. Lower your body until your chest nearly touches the floor. 4. Push back up to the starting position.' },
            { id: 'ex_decline_pushup', content: 'Decline Push-ups', type: 'log', target: { sets: 3, toFailure: true }, weight: 0, baseVolume: { weight: 0, reps: 10 }, requires: ['bodyweight'], history: [], primaryMuscle: 'upper_pectorals', secondaryMuscles: ['anterior_deltoid', 'triceps'], movementPattern: 'push_incline', difficulty: 'advanced', progression: 'ex_pushup', regression: null, environment: 'all', description: '1. Place your feet on an elevated surface like a bench or step. 2. Assume a push-up position with your hands on the floor. 3. Perform a push-up, focusing on the upper part of your chest.' },
            { id: 'ex_incline_pushup', content: 'Incline Push-ups', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15 }, weight: 0, baseVolume: { weight: 0, reps: 12 }, requires: ['bodyweight'], history: [], primaryMuscle: 'lower_pectorals', secondaryMuscles: ['triceps', 'anterior_deltoid'], movementPattern: 'push_horizontal', difficulty: 'beginner', progression: null, regression: 'ex_pushup', environment: 'all', description: '1. Place your hands on an elevated surface like a bench or wall. 2. Assume a push-up position with your feet on the floor. 3. Perform a push-up. The higher the surface, the easier the exercise.' },
            { id: 'ex_diamond_pushup', content: 'Diamond Push-ups', type: 'log', target: { sets: 3, toFailure: true }, weight: 0, baseVolume: { weight: 0, reps: 8 }, requires: ['bodyweight'], history: [], primaryMuscle: 'triceps', secondaryMuscles: ['pectorals'], movementPattern: 'push_horizontal', difficulty: 'advanced', progression: 'ex_pushup', regression: null, environment: 'all', description: '1. Assume a push-up position, but place your hands close together under your chest, forming a diamond shape with your thumbs and index fingers. 2. Perform a push-up, keeping your elbows tucked close to your body.' }
        ]
    },
    'Back': {
        barbell: [
            { id: 'ex_bent_over_row', content: 'Bent-Over Row', type: 'log', target: { sets: 3, minReps: 6, maxReps: 10 }, weight: 40, baseVolume: { weight: 40, reps: 8 }, requires: ['barbell'], history: [], primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'rhomboids', 'rear_deltoid'], movementPattern: 'pull_horizontal', difficulty: 'advanced', progression: 'ex_db_row', regression: null, environment: 'gym', description: '1. Stand with feet shoulder-width apart, holding a barbell with an overhand grip. 2. Hinge at your hips until your torso is nearly parallel to the floor, keeping your back straight. 3. Pull the barbell up towards your lower chest, squeezing your back muscles. 4. Lower the bar with control.' },
            { id: 'ex_pendlay_row', content: 'Pendlay Row', type: 'log', target: { sets: 3, minReps: 5, maxReps: 8 }, weight: 45, baseVolume: { weight: 45, reps: 6 }, requires: ['barbell'], history: [], primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'rhomboids'], movementPattern: 'pull_horizontal', difficulty: 'advanced', progression: 'ex_bent_over_row', regression: null, environment: 'gym', description: '1. Hinge at the hips with a flat back, gripping a barbell on the floor. 2. Explosively pull the bar from the floor to your lower chest. 3. Let the bar return to a dead stop on the floor after each rep.' }
        ],
        pullup_bar: [
            { id: 'ex_pullup', content: 'Pull-ups', type: 'log', target: { sets: 3, toFailure: true }, weight: 0, baseVolume: { weight: 0, reps: 5 }, requires: ['pullup_bar'], history: [], pro_tip: "Initiate the pull with your back muscles, not just your arms. Think about pulling your elbows down to your hips.", primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'rhomboids'], movementPattern: 'pull_vertical', difficulty: 'advanced', progression: 'ex_inverted_row', regression: null, environment: 'all', description: '1. Hang from a pull-up bar with an overhand grip, slightly wider than your shoulders. 2. Pull your body up until your chin is over the bar, driving your elbows down. 3. Lower yourself back down with control.' },
            { id: 'ex_chinup', content: 'Chin-ups', type: 'log', target: { sets: 3, toFailure: true }, weight: 0, baseVolume: { weight: 0, reps: 6 }, requires: ['pullup_bar'], history: [], primaryMuscle: 'biceps', secondaryMuscles: ['lats'], movementPattern: 'pull_vertical', difficulty: 'intermediate', progression: 'ex_inverted_row', regression: 'ex_pullup', environment: 'all', description: '1. Hang from a pull-up bar with an underhand, shoulder-width grip. 2. Pull your body up until your chin is over the bar, focusing on using your biceps. 3. Lower yourself back down with control.' }
        ],
        dumbbells_pair: [
            { id: 'ex_db_row', content: 'Dumbbell Row', type: 'log', target: { sets: 3, minReps: 8, maxReps: 12 }, weight: 15, baseVolume: { weight: 15, reps: 10 }, requires: ['dumbbells_pair', 'bench'], history: [], primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'rhomboids'], movementPattern: 'pull_horizontal', difficulty: 'intermediate', progression: 'ex_inverted_row', regression: 'ex_bent_over_row', environment: 'all', description: '1. Place one knee and hand on a bench, keeping your back flat. 2. Hold a dumbbell in the opposite hand with your arm extended. 3. Pull the dumbbell up towards your hip, squeezing your back muscles. 4. Lower the dumbbell slowly.' },
            { id: 'ex_incline_db_row', content: 'Incline Dumbbell Row', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15}, weight: 12, baseVolume: { weight: 12, reps: 12 }, requires: ['dumbbells_pair', 'bench'], history: [], primaryMuscle: 'lats', secondaryMuscles: ['rhomboids', 'rear_deltoid'], movementPattern: 'pull_horizontal', difficulty: 'intermediate', environment: 'all', description: '1. Set an incline bench to about 45 degrees and lie chest-down. 2. Hold a dumbbell in each hand with a neutral grip. 3. Squeeze your shoulder blades together and pull the dumbbells up towards your chest. 4. Lower with control.' },
        ],
        bodyweight: [{ id: 'ex_inverted_row', content: 'Inverted Rows', type: 'log', target: { sets: 3, toFailure: true }, weight: 0, baseVolume: { weight: 0, reps: 10 }, requires: ['bodyweight'], history: [], primaryMuscle: 'lats', secondaryMuscles: ['biceps', 'rhomboids'], movementPattern: 'pull_horizontal', difficulty: 'beginner', progression: null, regression: 'ex_pullup', environment: 'all', description: '1. Lie under a sturdy bar or table. 2. Grab the bar with an overhand grip and pull your chest up towards it, keeping your body in a straight line. 3. Lower yourself back down with control.' }]
    },
    'Legs': {
        barbell: [{ id: 'ex_barbell_squat', content: 'Barbell Back Squat', type: 'log', target: { sets: 3, minReps: 5, maxReps: 8 }, weight: 50, baseVolume: { weight: 50, reps: 6 }, requires: ['barbell'], history: [], pro_tip: "Keep your chest up and drive through your heels. Aim for your thighs to be at least parallel to the floor.", primaryMuscle: 'quadriceps', secondaryMuscles: ['glutes', 'hamstrings', 'adductors'], movementPattern: 'squat', difficulty: 'advanced', progression: 'ex_goblet_squat', regression: null, environment: 'gym', description: '1. Stand with feet shoulder-width apart, barbell resting on your upper back. 2. Keep your chest up and core braced, hinge at your hips and bend your knees to lower down. 3. Descend until thighs are parallel to the floor. 4. Drive through your heels to return to the start.' }],
        dumbbells_single: [ { id: 'ex_goblet_squat', content: 'Dumbbell Goblet Squat', type: 'log', target: { sets: 3, minReps: 8, maxReps: 12 }, weight: 13, baseVolume: { weight: 13, reps: 10 }, requires: ['dumbbells_single'], history: [], primaryMuscle: 'quadriceps', secondaryMuscles: ['glutes', 'core'], movementPattern: 'squat', difficulty: 'intermediate', progression: 'ex_bw_squat', regression: 'ex_barbell_squat', environment: 'all', description: '1. Stand with feet slightly wider than shoulder-width, holding one end of a dumbbell vertically against your chest. 2. Keeping your chest up, lower into a squat until your elbows touch your knees. 3. Drive through your heels to return to the start.' }],
        dumbbells_pair: [{ id: 'ex_bulgarian_split_squat', content: 'Bulgarian Split Squats', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15 }, weight: 8, baseVolume: { weight: 8, reps: 12 }, requires: ['dumbbells_pair', 'bench'], history: [], primaryMuscle: 'quadriceps', secondaryMuscles: ['glutes'], movementPattern: 'lunge', difficulty: 'intermediate', progression: 'ex_lunges', regression: null, environment: 'all', description: '1. Stand a few feet in front of a bench. Place the top of one foot on the bench behind you. 2. Holding dumbbells if using, lower your hips until your front thigh is parallel to the floor. 3. Push through your front foot to return to the start.' }],
        bodyweight: [
            { id: 'ex_bw_squat', content: 'Bodyweight Squats', type: 'log', target: { sets: 3, minReps: 15, maxReps: 20 }, weight: 0, baseVolume: { weight: 0, reps: 18 }, requires: ['bodyweight'], history: [], primaryMuscle: 'quadriceps', secondaryMuscles: ['glutes'], movementPattern: 'squat', difficulty: 'beginner', progression: null, regression: 'ex_goblet_squat', environment: 'all', description: '1. Stand with feet shoulder-width apart, chest up. 2. Lower your hips back and down as if sitting in a chair. 3. Keep your back straight and go as low as you comfortably can. 4. Push through your heels to stand back up.' },
            { id: 'ex_lunges', content: 'Lunges', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15 }, weight: 0, baseVolume: { weight: 0, reps: 12 }, requires: ['bodyweight'], history: [], primaryMuscle: 'quadriceps', secondaryMuscles: ['glutes'], movementPattern: 'lunge', difficulty: 'beginner', progression: null, regression: 'ex_bulgarian_split_squat', environment: 'all', description: '1. Step forward with one leg and lower your hips until both knees are bent at a 90-degree angle. 2. Ensure your front knee is directly above your ankle. 3. Push off your front foot to return to the starting position. Alternate legs.' },
            { id: 'ex_jump_squats', content: 'Jump Squats', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15 }, weight: 0, baseVolume: { weight: 0, reps: 12 }, requires: ['bodyweight'], history: [], primaryMuscle: 'quadriceps', secondaryMuscles: ['glutes', 'calves'], movementPattern: 'squat', difficulty: 'intermediate', progression: 'ex_bw_squat', regression: null, environment: 'all', description: '1. Perform a bodyweight squat. 2. From the bottom of the squat, explode upwards into a jump. 3. Land softly and immediately lower into the next squat.' }
        ]
    },
    'Hamstrings': {
         barbell: [
            { id: 'ex_barbell_rdl', content: 'Barbell Romanian Deadlift', type: 'log', target: { sets: 3, minReps: 8, maxReps: 12}, weight: 40, baseVolume: { weight: 40, reps: 10 }, requires: ['barbell'], history: [], primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes', 'lower_back'], movementPattern: 'hinge', difficulty: 'advanced', environment: 'gym', description: '1. Stand with feet hip-width apart, holding a barbell. 2. Keeping your back straight, hinge at your hips and lower the bar. 3. Go as low as you can without rounding your back. 4. Drive your hips forward to return to the start.' }
         ],
         dumbbells_single: [{ id: 'ex_db_rdl', content: 'Dumbbell Romanian Deadlift', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15 }, weight: 15, baseVolume: { weight: 15, reps: 12 }, requires: ['dumbbells_single'], history: [], primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes', 'lower_back'], movementPattern: 'hinge', difficulty: 'intermediate', progression: 'ex_bw_glute_bridge', regression: null, environment: 'all', description: '1. Stand with feet hip-width apart, holding a dumbbell in each hand. 2. Keeping your back straight, hinge at your hips and lower the weights. 3. Keep the dumbbells close to your legs. 4. Drive your hips forward to return to the start.' }],
         dumbbells_pair: [
            { id: 'ex_db_good_morning', content: 'Dumbbell Good Mornings', type: 'log', target: { sets: 3, minReps: 12, maxReps: 15}, weight: 10, baseVolume: { weight: 10, reps: 13 }, requires: ['dumbbells_pair'], history: [], primaryMuscle: 'hamstrings', secondaryMuscles: ['glutes', 'lower_back'], movementPattern: 'hinge', difficulty: 'intermediate', environment: 'all', description: '1. Stand with feet shoulder-width apart, holding two dumbbells on your shoulders. 2. Keeping your legs almost straight, hinge at your hips and lower your torso until it\'s parallel to the floor. 3. Keep your back straight throughout. 4. Return to the starting position.' }
         ],
         bands: [{ id: 'ex_banded_leg_curl', content: 'Banded Leg Curl', type: 'log', target: { sets: 3, minReps: 15, maxReps: 25 }, weight: 0, baseVolume: { weight: 0, reps: 20 }, requires: ['bands'], history: [], primaryMuscle: 'hamstrings', secondaryMuscles: [], movementPattern: 'curl', difficulty: 'beginner', progression: null, regression: null, environment: 'home', description: '1. Anchor a resistance band to a low point. 2. Lie on your stomach and loop the other end around your ankle. 3. Curl your heel towards your glute against the band\'s resistance. 4. Return with control.' }]
    },
    'Glutes': {
         barbell: [{ id: 'ex_hip_thrust', content: 'Barbell Hip Thrust', type: 'log', target: { sets: 3, minReps: 8, maxReps: 12 }, weight: 40, baseVolume: { weight: 40, reps: 10 }, requires: ['barbell', 'bench'], history: [], primaryMuscle: 'glutes', secondaryMuscles: ['hamstrings'], movementPattern: 'hinge', difficulty: 'advanced', progression: 'ex_db_glute_bridge', regression: null, environment: 'gym', description: '1. Sit on the floor with your upper back against a bench and a barbell across your hips. 2. Drive your hips up towards the ceiling, squeezing your glutes. 3. Your body should form a straight line from your shoulders to your knees. 4. Lower your hips back down with control.' }],
         dumbbells_single: [{ id: 'ex_db_glute_bridge', content: 'Dumbbell Glute Bridge', type: 'log', target: { sets: 3, minReps: 12, maxReps: 18 }, weight: 15, baseVolume: { weight: 15, reps: 15 }, requires: ['dumbbells_single'], history: [], primaryMuscle: 'glutes', secondaryMuscles: ['hamstrings'], movementPattern: 'hinge', difficulty: 'intermediate', progression: 'ex_bw_glute_bridge', regression: 'ex_hip_thrust', environment: 'all', description: '1. Lie on your back with your knees bent and feet flat on the floor. 2. Place a dumbbell across your hips. 3. Drive your hips up towards the ceiling, squeezing your glutes. 4. Lower your hips back down with control.' }],
         dumbbells_pair: [
            { id: 'ex_db_step_ups', content: 'Dumbbell Step-Ups', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15}, weight: 8, baseVolume: { weight: 8, reps: 12 }, requires: ['dumbbells_pair', 'bench'], history: [], primaryMuscle: 'glutes', secondaryMuscles: ['quadriceps'], movementPattern: 'lunge', difficulty: 'intermediate', environment: 'all', description: '1. Stand in front of a bench or step, holding dumbbells at your sides. 2. Step up onto the bench with one foot, driving through your heel. 3. Bring the other foot up to meet it. 4. Step back down and repeat, alternating the lead foot.' },
         ],
         bodyweight: [
            { id: 'ex_bw_glute_bridge', content: 'Bodyweight Glute Bridge', type: 'log', target: { sets: 3, minReps: 20, maxReps: 30 }, weight: 0, baseVolume: { weight: 0, reps: 25 }, requires: ['bodyweight'], history: [], primaryMuscle: 'glutes', secondaryMuscles: ['hamstrings'], movementPattern: 'hinge', difficulty: 'beginner', progression: null, regression: 'ex_db_glute_bridge', environment: 'all', description: '1. Lie on your back with your knees bent and feet flat on the floor. 2. Drive your hips up towards the ceiling, squeezing your glutes until you form a straight line from shoulders to knees. 3. Lower your hips back down with control.' },
            { id: 'ex_frog_pumps', content: 'Frog Pumps', type: 'log', target: { sets: 3, toFailure: true }, weight: 0, baseVolume: { weight: 0, reps: 30 }, requires: ['bodyweight'], history: [], primaryMuscle: 'glutes', secondaryMuscles: [], movementPattern: 'hinge', difficulty: 'beginner', progression: null, regression: null, environment: 'all', description: '1. Lie on your back with the soles of your feet together and knees out to the sides. 2. Drive your hips up towards the ceiling, focusing on squeezing your glutes. 3. Lower back down. The range of motion will be small.' }
        ]
    },
    'Shoulders': {
        barbell: [{ id: 'ex_overhead_press', content: 'Overhead Press', type: 'log', target: { sets: 3, minReps: 5, maxReps: 8 }, weight: 30, baseVolume: { weight: 30, reps: 6 }, requires: ['barbell'], history: [], primaryMuscle: 'anterior_deltoid', secondaryMuscles: ['triceps', 'medial_deltoid'], movementPattern: 'push_vertical', difficulty: 'advanced', progression: 'ex_db_shoulder_press', regression: null, environment: 'gym', description: '1. Stand with feet shoulder-width apart, holding a barbell at your shoulders with an overhand grip. 2. Brace your core and press the barbell directly overhead until your arms are fully extended. 3. Lower the bar back to your shoulders with control.' }],
        dumbbells_pair: [
            { id: 'ex_db_shoulder_press', content: 'Dumbbell Shoulder Press', type: 'log', target: { sets: 3, minReps: 8, maxReps: 12 }, weight: 10, baseVolume: { weight: 10, reps: 10 }, requires: ['dumbbells_pair'], history: [], primaryMuscle: 'anterior_deltoid', secondaryMuscles: ['triceps', 'medial_deltoid'], movementPattern: 'push_vertical', difficulty: 'intermediate', progression: 'ex_pike_pushup', regression: 'ex_overhead_press', environment: 'all', description: '1. Sit on a bench with back support, holding a dumbbell in each hand at shoulder height. 2. Press the dumbbells overhead until your arms are fully extended. 3. Lower the dumbbells back to your shoulders with control.' },
            { id: 'ex_lateral_raises', content: 'Lateral Raises', type: 'log', target: { sets: 3, minReps: 12, maxReps: 18 }, weight: 5, baseVolume: { weight: 5, reps: 15 }, requires: ['dumbbells_pair'], history: [], primaryMuscle: 'medial_deltoid', secondaryMuscles: [], movementPattern: 'raise', difficulty: 'beginner', progression: null, regression: null, environment: 'all', description: '1. Stand holding a dumbbell in each hand at your sides. 2. With a slight bend in your elbows, raise your arms out to your sides until they are parallel with the floor. 3. Lower the dumbbells back down with control.' }
        ],
        bodyweight: [{ id: 'ex_pike_pushup', content: 'Pike Push-ups', type: 'log', target: { sets: 3, toFailure: true }, weight: 0, baseVolume: { weight: 0, reps: 10 }, requires: ['bodyweight'], history: [], primaryMuscle: 'anterior_deltoid', secondaryMuscles: ['triceps'], movementPattern: 'push_vertical', difficulty: 'beginner', progression: null, regression: 'ex_db_shoulder_press', environment: 'all', description: '1. Get into a push-up position and walk your feet in, raising your hips into a downward dog pose. 2. Keeping your hips high, bend your elbows to lower the top of your head towards the floor. 3. Press back up to the starting position.' }]
    },
    'Arms': {
        dumbbells_pair: [
            { id: 'ex_bicep_curl', content: 'Bicep Curls', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15 }, weight: 10, baseVolume: { weight: 10, reps: 12 }, requires: ['dumbbells_pair'], history: [], primaryMuscle: 'biceps', secondaryMuscles: [], movementPattern: 'curl', difficulty: 'beginner', progression: null, regression: null, environment: 'all', description: '1. Stand holding a dumbbell in each hand with an underhand grip. 2. Keeping your elbows pinned to your sides, curl the weights up towards your shoulders. 3. Squeeze your biceps at the top, then lower the weights with control.' },
            { id: 'ex_tricep_extension', content: 'Overhead Tricep Extension', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15 }, weight: 8, baseVolume: { weight: 8, reps: 12 }, requires: ['dumbbells_pair'], history: [], primaryMuscle: 'triceps', secondaryMuscles: [], movementPattern: 'extension', difficulty: 'beginner', progression: null, regression: null, environment: 'all', description: '1. Sit or stand, holding one dumbbell with both hands overhead. 2. Lower the dumbbell behind your head by bending your elbows. 3. Extend your arms to raise the dumbbell back to the starting position.' }
        ],
        bodyweight: [{ id: 'ex_dips', content: 'Bench Dips', type: 'log', target: { sets: 3, toFailure: true }, weight: 0, baseVolume: { weight: 0, reps: 12 }, requires: ['bodyweight', 'bench'], history: [], primaryMuscle: 'triceps', secondaryMuscles: ['pectorals', 'anterior_deltoid'], movementPattern: 'push_vertical', difficulty: 'intermediate', progression: null, regression: null, environment: 'all', description: '1. Sit on the edge of a bench and place your hands on the edge, fingers forward. 2. Extend your legs out in front of you. 3. Slide your hips off the bench and lower your body by bending your elbows. 4. Push back up to the starting position.' }]
    },
    'Core': {
        pullup_bar: [
            { id: 'ex_hanging_knee_raises', content: 'Hanging Knee Raises', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15 }, weight: 0, baseVolume: { weight: 0, reps: 12 }, requires: ['pullup_bar'], history: [], primaryMuscle: 'core', secondaryMuscles: [], movementPattern: 'flexion', difficulty: 'intermediate', environment: 'all', description: '1. Hang from a pull-up bar with an overhand grip. 2. Keeping your legs together, raise your knees towards your chest. 3. Lower your legs back down with control, avoiding swinging.' },
            { id: 'ex_hanging_leg_raises', content: 'Hanging Leg Raises', type: 'log', target: { sets: 3, minReps: 8, maxReps: 12 }, weight: 0, baseVolume: { weight: 0, reps: 10 }, requires: ['pullup_bar'], history: [], primaryMuscle: 'core', secondaryMuscles: [], movementPattern: 'flexion', difficulty: 'advanced', environment: 'all', description: '1. Hang from a pull-up bar. 2. Keeping your legs straight, raise them up until they are parallel to the floor. 3. Lower your legs back down with control, avoiding any swinging.' }
        ],
        bodyweight: [
            { id: 'ex_plank', content: 'Plank', type: 'log', target: { sets: 3, timeInSeconds: 60 }, weight: 0, baseVolume: { weight: 0, reps: 60 }, requires: ['bodyweight'], history: [], primaryMuscle: 'core', secondaryMuscles: [], movementPattern: 'anti_extension', difficulty: 'beginner', progression: null, regression: null, environment: 'all', description: '1. Hold a push-up position, but with your weight resting on your forearms instead of your hands. 2. Keep your body in a straight line from head to heels, bracing your core and glutes. Hold for the prescribed time.' },
            { id: 'ex_crunches', content: 'Crunches', type: 'log', target: { sets: 3, minReps: 15, maxReps: 25 }, weight: 0, baseVolume: { weight: 0, reps: 20 }, requires: ['bodyweight'], history: [], primaryMuscle: 'core', secondaryMuscles: [], movementPattern: 'flexion', difficulty: 'beginner', environment: 'all', description: '1. Lie on your back with your knees bent and feet flat on the floor. 2. Place your hands behind your head or across your chest. 3. Lift your head and shoulder blades off the floor, crunching your abs. 4. Lower back down with control.' },
            { id: 'ex_leg_raises', content: 'Lying Leg Raises', type: 'log', target: { sets: 3, toFailure: true }, weight: 0, baseVolume: { weight: 0, reps: 15 }, requires: ['bodyweight'], history: [], primaryMuscle: 'core', secondaryMuscles: [], movementPattern: 'flexion', difficulty: 'intermediate', progression: null, regression: null, environment: 'all', description: '1. Lie on your back with your legs straight. 2. Keeping your legs straight, raise them up towards the ceiling until they are perpendicular to the floor. 3. Slowly lower them back down, stopping just before they touch the floor.' },
            { id: 'ex_vups', content: 'V-Ups', type: 'log', target: { sets: 3, minReps: 10, maxReps: 20 }, weight: 0, baseVolume: { weight: 0, reps: 15 }, requires: ['bodyweight'], history: [], primaryMuscle: 'core', secondaryMuscles: [], movementPattern: 'flexion', difficulty: 'advanced', environment: 'all', description: '1. Lie on your back with your arms extended behind your head. 2. In one motion, simultaneously lift your legs and torso up, reaching your hands towards your feet. 3. Your body should form a "V" shape at the top. 4. Lower back down with control.' },
            { id: 'ex_dead_bug', content: 'Dead Bug', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15 }, weight: 0, baseVolume: { weight: 0, reps: 12 }, requires: ['bodyweight'], history: [], primaryMuscle: 'core', secondaryMuscles: [], movementPattern: 'anti_extension', difficulty: 'beginner', progression: null, regression: null, environment: 'all', description: '1. Lie on your back with your arms extended towards the ceiling and your knees bent at 90 degrees. 2. Slowly lower your right arm and left leg towards the floor. 3. Return to the start and repeat with the opposite limbs.' },
            { id: 'ex_russian_twist', content: 'Russian Twists', type: 'log', target: { sets: 3, minReps: 15, maxReps: 20 }, weight: 0, baseVolume: { weight: 0, reps: 18 }, requires: ['bodyweight'], history: [], primaryMuscle: 'obliques', secondaryMuscles: ['core'], movementPattern: 'rotation', difficulty: 'beginner', progression: null, regression: 'ex_db_russian_twist', environment: 'all', description: '1. Sit on the floor with your knees bent and feet elevated. 2. Lean back slightly to engage your core. 3. Twist your torso from side to side, touching your hands to the floor on each side.' }
        ],
        dumbbells_single: [
            { id: 'ex_db_weighted_crunch', content: 'Weighted Crunches', type: 'log', target: { sets: 3, minReps: 12, maxReps: 20 }, weight: 5, baseVolume: { weight: 5, reps: 15 }, requires: ['dumbbells_single'], history: [], primaryMuscle: 'core', secondaryMuscles: [], movementPattern: 'flexion', difficulty: 'intermediate', environment: 'all', description: '1. Lie on your back with your knees bent, holding a dumbbell against your chest. 2. Perform a crunch, lifting your head and shoulder blades off the floor. 3. Lower back down with control.' },
            { id: 'ex_db_russian_twist', content: 'Dumbbell Russian Twists', type: 'log', target: { sets: 3, minReps: 12, maxReps: 18 }, weight: 5, baseVolume: { weight: 5, reps: 15 }, requires: ['dumbbells_single'], history: [], primaryMuscle: 'obliques', secondaryMuscles: ['core'], movementPattern: 'rotation', difficulty: 'intermediate', progression: 'ex_russian_twist', regression: null, environment: 'all', description: '1. Sit on the floor with your knees bent and feet elevated, holding a dumbbell with both hands. 2. Lean back slightly to engage your core. 3. Twist your torso from side to side, moving the dumbbell across your body.' }
        ],
        bands: [
            { id: 'ex_banded_cable_crunch', content: 'Banded Crunches', type: 'log', target: { sets: 3, minReps: 15, maxReps: 25 }, weight: 0, baseVolume: { weight: 0, reps: 20 }, requires: ['bands'], history: [], primaryMuscle: 'core', secondaryMuscles: [], movementPattern: 'flexion', difficulty: 'intermediate', environment: 'all', description: '1. Anchor a resistance band to a high point. 2. Kneel facing away from the anchor, holding the band on either side of your head. 3. Crunch your torso down towards the floor, engaging your abs. 4. Return to the start with control.' },
            { id: 'ex_pallof_press', content: 'Pallof Press', type: 'log', target: { sets: 3, minReps: 10, maxReps: 15 }, weight: 0, baseVolume: { weight: 0, reps: 12 }, requires: ['bands'], history: [], primaryMuscle: 'core', secondaryMuscles: ['obliques'], movementPattern: 'anti_rotation', difficulty: 'intermediate', progression: null, regression: null, environment: 'all', description: '1. Anchor a band at chest height. Stand sideways to the anchor and hold the band with both hands at your chest. 2. Press the band straight out in front of you, resisting the rotational pull from the band. 3. Bring it back to your chest with control.' }
        ]
    },
    'HIIT': {
        bodyweight: [
            { id: 'ex_burpees_hiit', content: 'Burpees HIIT', details: '5 min - 30s on, 30s off', duration: 300, type: 'timer', requires: ['bodyweight'], tags: ['hiit', 'cardio', 'full body', 'explosive'], primaryMuscle: 'full_body', movementPattern: 'dynamic', difficulty: 'advanced', environment: 'all', description: '1. From standing, drop into a squat and place your hands on the floor. 2. Kick your feet back to a plank position. 3. Immediately return your feet to the squat position. 4. Jump up explosively from the squat. Repeat.' },
            { id: 'ex_high_knees_hiit', content: 'High Knees HIIT', details: '5 min - 30s on, 30s off', duration: 300, type: 'timer', requires: ['bodyweight'], tags: ['hiit', 'cardio', 'full body'], primaryMuscle: 'full_body', movementPattern: 'dynamic', difficulty: 'intermediate', environment: 'all', description: '1. Stand in place and run, driving your knees up towards your chest as high as possible. 2. Maintain a fast pace for the duration of the work interval.' }
        ],
        jump_rope: [
            { id: 'ex_jump_rope_hiit', content: 'Jump Rope HIIT', details: '10 min - 45s on, 15s off', duration: 600, type: 'timer', requires: ['jump_rope'], tags: ['hiit', 'cardio', 'coordination'], primaryMuscle: 'full_body', movementPattern: 'dynamic', difficulty: 'intermediate', environment: 'all', description: '1. Jump with a rope at a consistent, fast pace. 2. Keep your feet close together and jump just high enough to clear the rope.' }
        ]
    },
    'Cardio': {
        bodyweight: [
            { id: 'ex_steady_walk', content: '30-Min Brisk Walk', details: '30 minutes', duration: 1800, type: 'info', requires: ['bodyweight'], tags: ['cardio', 'liss', 'recovery'], primaryMuscle: 'full_body', movementPattern: 'dynamic', difficulty: 'beginner', environment: 'all', description: 'Walk at a steady, brisk pace for 30 minutes, aiming to keep your heart rate in a low to moderate zone.' },
            { id: 'ex_steady_bike', content: '20-Min Stationary Bike', details: '20 minutes', duration: 1200, type: 'info', requires: ['bodyweight'], tags: ['cardio', 'liss', 'recovery'], primaryMuscle: 'full_body', movementPattern: 'dynamic', difficulty: 'beginner', environment: 'gym', description: 'Use a stationary bike for 20 minutes at a pace you can comfortably maintain a conversation at.' }
        ]
    },
    'Mobility': {
        bodyweight: [
            { id: 'recovery_hip_mobility', content: 'The Foundation: Hip Opening Flow', details: 'Approx. 11 min', duration: 670, type: 'info', requires: ['bodyweight'], routine: 'hip_mobility_flow', tags: ['mobility', 'yoga', 'hips', 'recovery'], primaryMuscle: 'hips', movementPattern: 'stretch', difficulty: 'beginner', environment: 'all', description: 'Purpose: To improve flexibility in your hips and glutes, which can help increase squat depth and reduce lower back discomfort.' },
            { id: 'recovery_spinal_decompression', content: 'Spinal Reset: Decompression Session', details: 'Approx. 12 min', duration: 720, type: 'info', requires: ['bodyweight', 'pullup_bar'], routine: 'spinal_decompression_flow', tags: ['mobility', 'yoga', 'spine', 'recovery'], primaryMuscle: 'spine', movementPattern: 'stretch', difficulty: 'beginner', environment: 'all', description: 'Purpose: To gently mobilize and create space in your spine, counteracting the compression from daily life and heavy lifting.' },
            { id: 'recovery_balance_core', content: 'Core Stability & Balance Builder', details: 'Approx. 10 min', duration: 570, type: 'info', requires: ['bodyweight'], routine: 'balance_core_flow', tags: ['mobility', 'balance', 'core', 'recovery'], primaryMuscle: 'core', movementPattern: 'stability', difficulty: 'beginner', environment: 'all', description: 'Purpose: To strengthen the deep core muscles that protect your spine and improve your balance, making your heavy lifts safer and stronger.' }
                ],
            }
        };

export const recoveryRoutineLibrary = {
    hip_mobility_flow: [
        { pose: '90/90 Hip Switches', duration: 60 },
        { pose: 'Frog Pose', duration: 90 },
        { pose: 'Pigeon Pose (Right)', duration: 90 },
        { pose: 'Pigeon Pose (Left)', duration: 90 },
        { pose: 'Deep Squat (Goblet) Hold', duration: 60 },
        { pose: 'Couch Stretch (Right)', duration: 60 },
        { pose: 'Couch Stretch (Left)', duration: 60 },
    ],
    spinal_decompression_flow: [
        { pose: 'Cat-Cow', duration: 90 },
        { pose: 'Thoracic Spine Rotations (Quadruped, Right)', duration: 60 },
        { pose: 'Thoracic Spine Rotations (Quadruped, Left)', duration: 60 },
        { pose: 'Child\'s Pose with Side Reach (Right)', duration: 60 },
        { pose: 'Child\'s Pose with Side Reach (Left)', duration: 60 },
        { pose: 'Passive Bar Hang', duration: 60 },
        { pose: 'Cobra Pose', duration: 60 },
        { pose: 'Supine Spinal Twists (Right)', duration: 60 },
        { pose: 'Supine Spinal Twists (Left)', duration: 60 },
    ],
    balance_core_flow: [
        { pose: 'Bird-Dog (Right)', duration: 60 },
        { pose: 'Bird-Dog (Left)', duration: 60 },
        { pose: 'Single-Leg Deadlift (Bodyweight, Right)', duration: 60 },
        { pose: 'Single-Leg Deadlift (Bodyweight, Left)', duration: 60 },
        { pose: 'Dead Bug', duration: 90 },
        { pose: 'Side Plank (Right)', duration: 45 },
        { pose: 'Side Plank (Left)', duration: 45 },
        { pose: 'Glute Bridge Hold', duration: 90 },
    ]
};

export const contraindications = {
    knees: ['ex_barbell_squat', 'ex_lunges', 'ex_jump_rope_hiit', 'ex_jump_squats'],
    shoulders: ['ex_overhead_press', 'ex_db_incline_press', 'ex_db_shoulder_press'],
    lower_back: ['ex_bent_over_row', 'ex_good_mornings', 'ex_barbell_rdl']
};

export const icons = { 
    log: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-dumbbell"><path d="m6.5 6.5 11 11"/><path d="m21 21-1-1"/><path d="m3 3 1 1"/><path d="m18 22 4-4"/><path d="m6 2 4 4"/><path d="m3 10 7-7"/><path d="m14 21 7-7"/></svg>', 
    diet: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-utensils-crossed"><path d="m16 2-2.3 2.3a3 3 0 0 0 0 4.2l1.8 1.8a3 3 0 0 0 4.2 0L22 8Z"/><path d="M15 15 3.3 3.3a4.2 4.2 0 0 0 0 6l7.3 7.3c.7.7 1.8.7 2.5 0l7.3-7.3a4.2 4.2 0 0 0 0-6L15 15Z"/></svg>', 
    history: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-history"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/></svg>', 
    swap: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-repeat"><path d="m17 2 4 4-4 4"/><path d="M3 11v-1a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v1a4 4 0 0 1-4 4H3"/></svg>',
    info: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-info"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></svg>',
    badge: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-award"><circle cx="12" cy="8" r="6"/><path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11"/></svg>',
    export: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-download"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>'
};
